populate.sql
tests/Fixture/TypeUsersFixture.php
tests/TestCase/Model/Table/TypeUsersTableTest.php
tests/TestCase/Model/Table/UsersTableTest.php

| Tickets (_issues_) concernés  | #19

Fixed syntax errors of type_users role

---

src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #22

Add delete permission for Administrator

---

config/Migrations/20150916173706_modify_gender_to_boolean.php
src/Model/Table/UsersTable.php

| Tickets (_issues_) concernés  | #21

Boolean in user gender

---

src/Controller/CommentsController.php
src/Controller/MissionsController.php
src/Controller/OrganizationsController.php
src/Controller/OrganizationsProjectsController.php
src/Controller/ProjectsController.php
src/Controller/ProjectsUsersController.php
src/Controller/ProjectsUsersMissionsController.php
src/Controller/SvnUsersController.php
src/Controller/SvnsController.php
src/Controller/TypeUsersController.php
src/Controller/UniversitiesController.php
src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #30

Added permissions and isAuthorized to all controller

---

tests/Fixture/ProjectsFixture.php
tests/Fixture/TypeUsersUsersFixture.php
tests/Fixture/UsersFixture.php
tests/TestCase/Controller/CommentsControllerTest.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Controller/OrganizationsControllerTest.php
tests/TestCase/Controller/OrganizationsProjectsControllerTest.php
tests/TestCase/Controller/ProjectsControllerTest.php
tests/TestCase/Controller/ProjectsUsersControllerTest.php
tests/TestCase/Controller/ProjectsUsersMissionsControllerTest.php
tests/TestCase/Controller/SvnUsersControllerTest.php
tests/TestCase/Controller/SvnsControllerTest.php
tests/TestCase/Controller/TypeUsersControllerTest.php
tests/TestCase/Controller/UniversitiesControllerTest.php
tests/TestCase/Controller/UsersControllerTest.php
tests/TestCase/Model/Table/CommentsTableTest.php
tests/TestCase/Model/Table/MissionsTableTest.php
tests/TestCase/Model/Table/OrganizationsProjectsTableTest.php
tests/TestCase/Model/Table/OrganizationsTableTest.php
tests/TestCase/Model/Table/ProjectsTableTest.php
tests/TestCase/Model/Table/ProjectsUsersMissionsTableTest.php
tests/TestCase/Model/Table/ProjectsUsersTableTest.php
tests/TestCase/Model/Table/SvnUsersTableTest.php
tests/TestCase/Model/Table/SvnsTableTest.php
tests/TestCase/Model/Table/TypeUsersTableTest.php
tests/TestCase/Model/Table/TypeUsersUsersTableTest.php
tests/TestCase/Model/Table/UniversitiesTableTest.php
tests/TestCase/Model/Table/UsersTableTest.php

| Tickets (_issues_) concernés  | #15

Controller tests

---

tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #35

Add the test for the newly confirm fields in the register and add tests

---

src/Template/Pages/home.ctp

| Tickets (_issues_) concernés  | #25 
Ajout du formulaire étudiant pour la journée des clubs. 
Simple modification du template home

Add form on homepage in a spoiler

---

src/Template/Layout/default.ctp
webroot/js/googleAnalytics.js

| Tickets (_issues_) concernés  | #26 
Ajout d'un fichier JS contenant le script de Google Analytics
Importation du script dans ../Layout/default.ctp

Add google Analytics and import in the default layout

---

composer.json

| Tickets (_issues_) concernés  | #3

Added mll/apisvn to composer

---

src/Model/Table/OrganizationsTable.php
src/Template/Organizations/add.ctp

| Nouvelle Fonctionnalité ?     | oui
| Tickets (_issues_) concernés  | #10 
Organizations.website is now allowEmpty

Implement addOrganization

---

README.md

| Tickets (_issues_) concernés  | #45

Rebadge to develop branch

---

README.md

| Tickets (_issues_) concernés  | #45

Fixed ready badge link

---

config/Migrations/20150922143329_add_is_validated_to_organizations.php
config/Migrations/20150922143348_add_is_rejected_to_organizations.php
src/Controller/OrganizationsController.php
src/Model/Entity/Organization.php
src/Model/Table/OrganizationsTable.php
src/Template/Organizations/submit.ctp
tests/Fixture/OrganizationsFixture.php
tests/TestCase/Controller/OrganizationsControllerTest.php

| Tickets (_issues_) concernés  | #52 
Add submit method
Add two columns on Organizations table (isValidated and isRejected)
Update index  to show only organization who are validated and not rejected
Update add to set organization->isValidated to true

Submit organization

---

.gitignore

| Tickets (_issues_) concernés  | #58
Update gitIgnore to add tmp/* and logs/*

Add tmp/* and logs/* in gitignore

---

src/Controller/ProjectsController.php
src/Model/Table/ProjectsTable.php
src/Template/Projects/add.ctp

| Tickets (_issues_) concernés  | #7 
Required fields to add a project:
- Name
- Description
Optionnal fields:
- Link (repo)
- Organizations

Implement addProject

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #67
Just move a line at the end of the page to debug import of JQuery
Add a warning message

Move the fetch of scriptBottom at the end

---

src/Controller/ProjectsController.php
src/Model/Table/ProjectsTable.php
src/Template/Projects/index.ctp

| Correction de bugs ?          | NON
| Tickets (_issues_) concernés  | #89 
- Change list to show only the name of the repository

Update project index

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #92 #90 
Add id of user in session

Add id of current session

---

src/Template/Users/register.ctp

| Tickets (_issues_) concernés  | #94 
- Delete actions panels on left of register page

Delete actions on register page

---

src/Controller/ProjectsController.php
src/Model/Entity/OrganizationsProject.php
src/Model/Table/OrganizationsProjectsTable.php
src/Model/Table/ProjectsTable.php
src/Template/Element/Projects/sidebar.ctp
src/Template/Projects/edit.ctp
src/Template/Projects/view.ctp
tests/Fixture/OrganizationsProjectsFixture.php
tests/TestCase/Controller/ProjectsControllerTest.php

| Tickets (_issues_) concernés  | #8 
Update view
Implement edit

Design view and implement edit of project

---

src/Controller/UsersController.php
src/Model/Table/UsersTable.php
src/Template/Element/Users/sidebar.ctp
src/Template/Users/email.ctp
tests/Fixture/TypeUsersUsersFixture.php
tests/Fixture/UsersFixture.php
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #5

Edit email

---

src/Controller/UsersController.php
src/Template/Element/Users/sidebar.ctp
src/Template/Users/password.ctp
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #5

Edit password

---

src/Controller/OrganizationsController.php
src/Model/Table/OrganizationsTable.php
src/Template/Element/Organizations/sidebar.ctp
src/Template/Organizations/view.ctp
tests/TestCase/Controller/OrganizationsControllerTest.php

| Tickets (_issues_) concernés  | #98  
- Add regex on organization->website
- Update view
- Redirect on view after edition of organization

Organization view

---

src/Controller/UsersController.php
src/Template/Users/index.ctp

| Tickets (_issues_) concernés  | #107

User index simplify

---

src/Template/Organizations/index.ctp

| Tickets (_issues_) concernés  | #108

Modify organization index (removed action and other cosmetic fix)

---

src/Template/Pages/partner.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #116

Partner page responsive

---

src/Template/Pages/home.ctp

| Tickets (_issues_) concernés  | #115

Front page responsive

---

src/Template/Pages/home.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #117

Home side by side text

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #132 
Just delete debug call

delete debug call

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #135

Change variable to debug applyproject

---

src/Template/Pages/home.ctp

| Tickets (_issues_) concernés  | #119

Add en/fr detection for survey

---

src/Template/Layout/default.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #51

Sticky footer

---

src/Template/Pages/home.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #115

Responsive banner

---

src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php
src/Controller/UsersController.php
src/Template/Element/Organizations/sidebar.ctp
src/Template/Element/Projects/sidebar.ctp
src/Template/Organizations/view.ctp
src/Template/Projects/view.ctp
tests/TestCase/Controller/OrganizationsControllerTest.php
tests/TestCase/Controller/ProjectsControllerTest.php
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #148 
Add before filter on Organizations, Projects and Users controller
Modify template and particulary sidebar condition

Add before filter and update template

---

src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #152

Encryption for password when modify

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #143 
Redirect to current page on language change
Fixed ML2 button home redirect

Redirect to current page when changing language

---

src/Controller/AppController.php
src/Controller/UsersController.php
src/Template/Layout/default.ctp
tests/TestCase/Controller/AppControllerTest.php

| Tickets (_issues_) concernés  | #185

Redirect login

---

src/Controller/ProjectsController.php
src/Model/Table/ProjectsTable.php
src/Template/Element/Projects/actionSidebar.ctp
src/Template/Element/Projects/sidebar.ctp
src/Template/Projects/admin_index.ctp
src/Template/Projects/index.ctp
tests/Fixture/ProjectsFixture.php
tests/TestCase/Controller/ProjectsControllerTest.php
webroot/js/projects/adminIndex.js
webroot/js/projects/index.js

| Tickets (_issues_) concernés  | #9

Approve project

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #192

Removed var_dump

---

src/Model/Table/UsersTable.php
src/Template/Users/edit.ctp

| Tickets (_issues_) concernés  | #169

Add the not specified choice in the user profile for university

---

config/bootstrap.php
tests/TestCase/Controller/AppControllerTest.php

| Tickets (_issues_) concernés  | #194

Changed default language to fr_CA

---

src/Controller/UsersController.php
src/Model/Entity/User.php
src/Template/Users/edit.ctp
tests/Fixture/UsersFixture.php
tests/TestCase/Controller/UsersControllerTest.php
tests/TestCase/Model/Table/UsersTableTest.php

| Tickets (_issues_) concernés  | #86
+I add tests for users (getNameNull)

Add the not specified choice for gender

---

src/Controller/UsersController.php
src/Template/Element/Users/sidebar.ctp
src/Template/Organizations/admin_index.ctp
src/Template/Organizations/index.ctp
src/Template/Users/email.ctp
src/Template/Users/index.ctp
src/Template/Users/register.ctp
webroot/js/organizations/adminIndex.js
webroot/js/organizations/index.js
webroot/js/users/index.js

| Tickets (_issues_) concernés  | #183 #173 #40 #168

Visual bugs org n users

---

src/Controller/UsersController.php
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #200

Login redirect

---

src/Controller/UsersController.php
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #139

Redirect user if he tries to change password of other user

---

src/Controller/UsersController.php
src/Template/Users/register.ctp

| Tickets (_issues_) concernés  | #209

Add university to register

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #213

Changed menu layout

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #227 
Link user in session as mentor of the project created/submitted

Add mentor on project when submit or add

---

composer.json

| Tickets (_issues_) concernés  | #242 
Make sure composer does not load from cache

Forced version 3.1.1 of CakePHP

---

src/Template/Cell/Sidebar/user.ctp

| Tickets (_issues_) concernés  | #238 
Just add a message on the sidebar to redirect on gravatar.

Add informations and link to gravatar in sidebar user

---

src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #236 
Select fields set on datable.

Select fields on datatable for security

---

src/Template/Users/login.ctp

| Tickets (_issues_) concernés  | #252 
Add button register on login page
Add bootstrap coloration on login button

add button register on login page

---

src/Model/Table/MissionsTable.php
src/Template/Missions/add.ctp
src/Template/Missions/view.ctp
tests/TestCase/Controller/MissionsControllerTest.php

| Tickets (_issues_) concernés  | #260

Tuning mission

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #269

In the project view show only mission associated with the project

---

src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php
tests/TestCase/Controller/OrganizationsControllerTest.php
tests/TestCase/Controller/ProjectsControllerTest.php

| Tickets (_issues_) concernés  | #266 #267 
Just change redirection after creation

Redirect after submit or add project or org

---

src/Template/Users/register.ctp

| Tickets (_issues_) concernés  | #272 
Set horizontal form
Add button to login page
Add space between all part of the form

Refont of register page

---

src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php
src/Template/Organizations/index.ctp
src/Template/Projects/index.ctp
webroot/css/ML2-styles.css
webroot/js/organizations/index.js
webroot/js/projects/index.js

| Tickets (_issues_) concernés  | #241

Label&security on data table

---

src/Template/Pages/home.ctp

look at the todo comments in home.ctp
tested for resposniveness

new home page for ML2

---

src/Controller/ProjectsController.php
src/Template/Projects/submit.ctp

| Tickets (_issues_) concernés  | #279

Organizations filter

---

src/Template/Cell/Sidebar/organization.ctp

| Tickets (_issues_) concernés  | #268 
Add button "add" and "sumbit" project to organization sidebar

Add actions in organization sidebar

---

src/Template/Users/view.ctp

| Tickets (_issues_) concernés  | #281 #280 
Add table of project mentored in user page
Add table of organization joined in user page
Add badge in table

Add table of project and organization

---

src/Template/Organizations/add.ctp
src/Template/Organizations/edit.ctp
src/Template/Organizations/submit.ctp

| Tickets (_issues_) concernés  | #276 
Remove organization's logo on add/submit/edit page

Remove organization's logo on add/submit/edit page

---

src/Template/Organizations/add.ctp
src/Template/Organizations/submit.ctp
src/Template/Projects/add.ctp
src/Template/Projects/submit.ctp

| Tickets (_issues_) concernés  | #253 #254 
Just add text on add/submit of project and organization

add some info text on form page

---

src/Template/Organizations/view.ctp

| Tickets (_issues_) concernés  | #290 
Add badge : 
- in pending
- archived

add badge on project in organization view

---

src/Controller/AppController.php
src/Template/Layout/default.ctp
src/Template/Users/login.ctp

| Tickets (_issues_) concernés  | #304

Change the authError message and add an error class if fail

---

src/Template/Projects/view.ctp

| Tickets (_issues_) concernés  | #305

Project description low resolution problem

---

src/Template/Layout/default.ctp
src/Template/Missions/add.ctp
src/Template/Missions/view.ctp
src/Template/Organizations/add.ctp
src/Template/Organizations/add_member.ctp
src/Template/Organizations/add_owner.ctp
src/Template/Organizations/admin_index.ctp
src/Template/Organizations/edit.ctp
src/Template/Organizations/index.ctp
src/Template/Organizations/quit.ctp
src/Template/Organizations/submit.ctp
src/Template/Organizations/view.ctp
src/Template/Projects/add.ctp
src/Template/Projects/admin_index.ctp
src/Template/Projects/apply.ctp
src/Template/Projects/edit.ctp
src/Template/Projects/index.ctp
src/Template/Projects/submit.ctp
src/Template/Users/delete.ctp
src/Template/Users/edit.ctp
src/Template/Users/email.ctp
src/Template/Users/index.ctp
src/Template/Users/login.ctp
src/Template/Users/password.ctp
src/Template/Users/register.ctp
src/Template/Users/view.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #309 
The PR #307 must be accepted before this one because this PR is based on it

Refactor template page

---

src/Controller/ProjectsController.php
src/Template/Projects/view.ctp
webroot/js/projects/view.js

| Tickets (_issues_) concernés  | #312

Add new collumn

---

src/Template/Pages/home.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #318

Create the class hr-black for the homepage

---

src/Template/Users/login.ctp
src/Template/Users/register.ctp

| Tickets (_issues_) concernés  | #327 
Change button to link
Change text on login page to be more explicit

change button to link

---

config/Migrations/20151023191904_add_archived_to_missions.php
src/Controller/MissionsController.php
src/Controller/ProjectsController.php
src/Model/Entity/Mission.php
src/Model/Table/MissionsTable.php
src/Template/Cell/Sidebar/mission.ctp
src/Template/Missions/edit.ctp
src/Template/Missions/view.ctp
src/Template/Projects/view.ctp
src/View/Cell/SidebarCell.php
tests/Fixture/MissionsFixture.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Model/Table/MissionsTableTest.php
webroot/js/projects/view.js

| Tickets (_issues_) concernés  | #294 
Add sidebar for mission
implement functionnality "archive/restore mission"
implement functionnality "edit mission"

Edit missions

---

webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #331
Fix Add space between content and footer #331

Fix Add space between content and footer #331

---

SETUP.md

| Tickets (_issues_) concernés  | #296 
Update setup.md to add directive about composer
Delete obsolete directive about the app.php

Upgrade Setup with composer detail

---

src/Template/Cell/Sidebar/mission.ctp
src/Template/Cell/Sidebar/organization.ctp
src/Template/Cell/Sidebar/project.ctp
src/Template/Cell/Sidebar/user.ctp

| Tickets (_issues_) concernés  | #277 
update icon in all sidebar

change icon on sidebars

---

src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #350 
Redirect on user page (users/view/) if the user have no provenance when it come on login page.

Redirect on user page after login if no provenance

---

src/Template/Cell/Sidebar/organization.ctp

| Tickets (_issues_) concernés  | #351 
Add organization's page
Refactor sidebar to conditionning coloration

Add organization's page and add conditionning coloration

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #363

Search by organizations crash

---

src/Controller/AppController.php
src/Template/Missions/add.ctp
src/Template/Organizations/index.ctp
src/Template/Organizations/submit.ctp
src/Template/Organizations/view.ctp
src/Template/Projects/index.ctp
src/Template/Projects/submit.ctp
src/Template/Projects/view.ctp
src/Template/Users/view.ctp
src/View/Helper/WikiHelper.php
tests/TestCase/View/Helper/WikiHelperTest.php

| Tickets (_issues_) concernés  | #328 
Create WikiHelper
- buildLink(pageName) -> return the URL to the wiki page
- `linkToWikiPage`
- addHelper(pageName) -> return an helper who link to the wiki page
- `<a href="linkToWikiPage">iconQuestionOfFontAwesome</a>`
Add some helper on some template

Add helper to wiki

---

webroot/js/projects/submit.js

| Tickets (_issues_) concernés  | #366

Show error message when submitting

---

src/Template/Element/Missions/addForm.ctp
src/Template/Missions/add.ctp
src/Template/Missions/edit.ctp
src/Template/Organizations/add.ctp
src/Template/Organizations/edit.ctp
src/Template/Organizations/submit.ctp
src/Template/Organizations/view.ctp
src/Template/Projects/add.ctp
src/Template/Projects/edit.ctp
src/Template/Projects/submit.ctp
src/Template/Users/edit.ctp
src/Template/Users/view.ctp

| Tickets (_issues_) concernés  | #352

Add markdown

---

config/Migrations/20151030152039_create_hash.php
config/Migrations/20151030152105_create_hash_type.php
config/app.php
phpunit.xml.dist
populate.sql
src/Controller/Component/HashComponent.php
src/Controller/UsersController.php
src/Mailer/UserMailer.php
src/Model/Entity/Hash.php
src/Model/Entity/HashType.php
src/Model/Entity/User.php
src/Model/Table/HashTypesTable.php
src/Model/Table/HashesTable.php
src/Model/Table/UsersTable.php
src/Template/Email/html/reset_password.ctp
src/Template/Email/text/reset_password.ctp
src/Template/Email/text/user.ctp
src/Template/Layout/Email/html/user.ctp
src/Template/Layout/Email/text/user.ctp
src/Template/Users/login.ctp
src/Template/Users/recover_password.ctp
src/Template/Users/reset_password.ctp
tests/Fixture/HashTypesFixture.php
tests/Fixture/HashesFixture.php
tests/TestCase/Controller/Component/HashComponentTest.php
tests/TestCase/Controller/UsersControllerTest.php
tests/TestCase/Mailer/UserMailerTest.php
tests/TestCase/Model/Table/HashTypesTableTest.php
tests/TestCase/Model/Table/HashesTableTest.php

| Tickets (_issues_) concernés  | #322 
You need to :
- Migrate DB
- Populate hashTypes
- Configure Email in Mailer and config file 'app.php'

Recover password

---

webroot/js/projects/submit.js

| Tickets (_issues_) concernés  | #376

Make the link add mission work

---

config/Migrations/20151103135810_drop_applications.php
config/Migrations/20151103135829_create_applications.php
config/app.php
populate.sql
src/Controller/MissionsController.php
src/Mailer/ApplicationMailer.php
src/Model/Entity/Application.php
src/Model/Entity/Mission.php
src/Model/Table/ApplicationsTable.php
src/Model/Table/MissionsTable.php
src/Template/Email/html/new_application.ctp
src/Template/Email/text/new_application.ctp
src/Template/Missions/apply.ctp
src/Template/Missions/view.ctp
tests/Fixture/ApplicationsFixture.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Model/Table/ApplicationsTableTest.php
tests/TestCase/Model/Table/MissionsTableTest.php
webroot/js/missions/view.js

| Tickets (_issues_) concernés  | #321
Reminder : Migrations

Application

---

src/Template/Projects/submit.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #333

[Release] Asterisk required

---

src/Template/Email/html/new_application.ctp
src/Template/Email/html/reset_password.ctp
src/Template/Email/text/new_application.ctp

| Tickets (_issues_) concernés  | #380 
Change template of mailer to fix Url bug

[Release] fix Url in Mailer template

---

src/Controller/MissionsController.php

| Tickets (_issues_) concernés  | #382

[Release] Block application if already applied

---

src/Template/Missions/view.ctp

| Tickets (_issues_) concernés  | #388

[Release] hide rejected/accepted button on mission view

---

config/routes.php
src/Controller/AppController.php
src/Controller/PagesController.php
src/Template/Pages/home.ctp
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #387

[Release] change route to home page and add statistics

---

src/Template/Cell/Sidebar/user.ctp
src/Template/Missions/apply.ctp
src/Template/Missions/view.ctp
src/Template/Pages/contact.ctp
src/Template/Users/recover_password.ctp

| Tickets (_issues_) concernés  | #383

[Release] Text change

---

src/Template/Element/Missions/addForm.ctp
src/Template/Missions/edit.ctp
src/Template/Organizations/add.ctp
src/Template/Organizations/edit.ctp
src/Template/Organizations/submit.ctp
src/Template/Projects/add.ctp
src/Template/Projects/edit.ctp
src/Template/Projects/submit.ctp
src/Template/Users/edit.ctp

| Tickets (_issues_) concernés  | #390

[Release] How-to Markdown

---

src/Template/Projects/submit.ctp
webroot/js/projects/submit.js

| Tickets (_issues_) concernés  | #388

[Release] Add url validation project

---

webroot/js/projects/submit.js

| Tickets (_issues_) concernés  | #402

[Release] Change mission tab text in creation project

---

src/Controller/MissionsController.php
src/Controller/ProjectsController.php
src/Template/Missions/view.ctp

| Tickets (_issues_) concernés  | #400

[Release] Datatable security

---

composer.json

| Tickets (_issues_) concernés  | #398

Unfreeze the cakephp version

---

src/Template/Organizations/view.ctp

| Tickets (_issues_) concernés  | #393

Put a badge if owner organization

---

src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #399

[Release] Change redirection when login

---

src/Template/Users/recover_password.ctp

| Tickets (_issues_) concernés  | #406

add translation on recoverPassword

---

webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #412

[Release] Remove the asterisk on multiselect label

---

src/Model/Table/UsersTable.php
src/Template/Users/register.ctp

| Tickets (_issues_) concernés  | #411

[Release] Validation username

---

src/Template/Pages/home.ctp

| Tickets (_issues_) concernés  | #416

[Release] Change the sponsor text

---

src/Template/Email/html/new_application.ctp
src/Template/Email/html/reset_password.ctp
src/Template/Email/text/new_application.ctp
src/Template/Email/text/reset_password.ctp

| Tickets (_issues_) concernés  | #414

[Release] Change text of email

---

src/Controller/MissionsController.php
webroot/js/missions/view.js

| Tickets (_issues_) concernés  | #418

[Release] Change Jquery for mission applications

---

src/View/Helper/WikiHelper.php

| Tickets (_issues_) concernés  | #424

set link to wiki blank

---

src/Template/Element/News/news-table.ctp

| Tickets (_issues_) concernés  | #426

remove status of website on news element

---

src/Controller/MissionsController.php
src/Controller/ProjectsController.php
src/Model/Entity/Project.php
src/Model/Table/MissionsTable.php
src/Template/Cell/Sidebar/mission.ctp
src/Template/Cell/Sidebar/project.ctp
src/Template/Missions/edit_mentor.ctp
src/Template/Missions/view.ctp
src/Template/Projects/edit_mentor.ctp
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Controller/ProjectsControllerTest.php
tests/TestCase/Model/Table/ProjectsTableTest.php
webroot/js/missions/edit-mentor.js
webroot/js/projects/edit-mentor.js

| Tickets (_issues_) concernés  | #295
Edit project mentors
Edit mission mentor
Remove mission mentor if not project mentors anymore

Edit project mission mentors

---

src/Controller/UsersController.php
src/Model/Table/UsersTable.php
src/Template/Users/register.ctp
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #425

isStudent set to true by default

---

src/Controller/UsersController.php
src/Template/Users/password.ctp
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #437

[Hotfix] Add validation for old and confirm password

---

src/Template/Layout/default.ctp
src/Template/Pages/gov.ctp

| Tickets (_issues_) concernés  | #442

[hotfix] delete montreal partners and gov in navbar

---

src/Mailer/ApplicationMailer.php

| Tickets (_issues_) concernés  | #452

[Hotfix] Change name to username

---

src/View/Helper/GoogleChartHelper.php

| Tickets (_issues_) concernés  | #432 
Add GoogleChartHelper

add GoogleChartHelper

---

src/Mailer/ApplicationMailer.php
src/Mailer/UserMailer.php
src/Template/Email/html/new_application.ctp
src/Template/Email/html/reset_password.ctp
src/Template/Email/text/new_application.ctp
src/Template/Email/text/reset_password.ctp

| Tickets (_issues_) concernés  | #434

Translation mail

---

src/Controller/ProjectsController.php
src/Mailer/ProjectMailer.php
src/Template/Email/html/approve_project.ctp
src/Template/Email/html/archive_project.ctp
src/Template/Email/html/unarchive_project.ctp
src/Template/Email/text/approve_project.ctp
src/Template/Email/text/archive_project.ctp
src/Template/Email/text/unarchive_project.ctp
tests/TestCase/Controller/ProjectsControllerTest.php

| Tickets (_issues_) concernés  | #431 
Send a mail to all mentor of the project when we : 
- Approve a project
- Archive a project
- Unarchive a project

Send mail project

---

src/Controller/OrganizationsController.php
webroot/js/organizations/adminIndex.js

| Tickets (_issues_) concernés  | #455

[Hotfix] Cast boolean switch org

---

src/Template/Cell/Sidebar/user.ctp

| Tickets (_issues_) concernés  | #459

Space problem

---

src/Model/Entity/Organization.php

| Tickets (_issues_) concernés  | #359

Archive all projects when archive an organizations

---

config/app.php
config/app_travis.php
src/Controller/ApplicationsController.php
src/Controller/MissionsController.php
src/Mailer/ApplicationMailer.php
src/Model/Entity/Application.php
src/Model/Entity/Mission.php
src/Template/Applications/accepted.ctp
src/Template/Applications/rejected.ctp
src/Template/Email/html/accepted_on_application.ctp
src/Template/Email/html/reject_no_more_position.ctp
src/Template/Email/html/rejected_on_application.ctp
src/Template/Email/text/accepted_on_application.ctp
src/Template/Email/text/reject_no_more_position.ctp
src/Template/Email/text/rejected_on_application.ctp
src/Template/Missions/view.ctp
tests/Fixture/ApplicationsFixture.php
tests/Fixture/MissionsFixture.php
tests/Fixture/PermissionsFixture.php
tests/Fixture/PermissionsTypeUsersFixture.php
tests/Fixture/TypeUsersUsersFixture.php
tests/Fixture/UsersFixture.php
tests/TestCase/Controller/ApplicationsControllerTest.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Model/Table/MissionsTableTest.php
webroot/js/missions/view.js
webroot/js/missions/viewMentor.js

| Tickets (_issues_) concernés  | #14 #325 #220

Edit status application

---

src/Template/Organizations/admin_index.ctp
src/Template/Organizations/index.ctp
src/Template/Projects/admin_index.ctp
src/Template/Projects/index.ctp
src/Template/Users/index.ctp

| Tickets (_issues_) concernés  | #461 
Set default number of row to 50 (actually 10)

change default number in datatable index

---

src/Template/Cell/Sidebar/mission.ctp

| Tickets (_issues_) concernés  | #464

delete unset variable in template

---

src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #470

change Access Modifiers on adminIndex

---

src/Controller/MissionsController.php

| Tickets (_issues_) concernés  | #471 
Redirect on homepage if apply on a mission when project is archived or not accepted

redirect on homepage if apply on mission not authorized

---

src/Controller/MissionsController.php
src/Template/Missions/view.ctp

| Tickets (_issues_) concernés  | #465

fix bug of display on mission view

---

src/Template/Missions/edit.ctp

| Tickets (_issues_) concernés  | #481

add row in edit mission

---

src/Controller/ApplicationsController.php
src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php
src/Model/Entity/ProjectsContributor.php
src/Model/Entity/User.php
src/Model/Table/ProjectsContributorsTable.php
src/Template/Layout/default.ctp
src/Template/Organizations/my_org.ctp
src/Template/Organizations/my_organizations.ctp
src/Template/Projects/my_projects.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #385 #478

Refactor menu user

---

src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #484

Fix dt count

---

config/routes.php
src/Controller/PagesController.php
src/Template/Pages/tv1.ctp
src/Template/Pages/tv3.ctp

| Tickets (_issues_) concernés  | #500
The TV 3 need some change, but right now all link point to the ctp 1

Add tv support

---

src/Template/Error/error400.ctp

| Tickets (_issues_) concernés  | #492

change 400 page error

---

src/Controller/PagesController.php

| Tickets (_issues_) concernés  | #502

Add coding standards ignore for pagesController

---

config/Migrations/20151116190721_create_svn_projects.php
config/Migrations/20151116192926_add_repository_link_to_projects.php
config/Migrations/20151116195155_create_statistics.php
config/routes.php
src/Controller/PagesController.php
src/Model/Entity/Statistic.php
src/Model/Table/ProjectsTable.php
src/Model/Table/StatisticsTable.php
src/Template/Layout/default.ctp
src/Template/Pages/statistics.ctp
tests/Fixture/StatisticsFixture.php
tests/TestCase/Controller/PagesControllerTest.php
tests/TestCase/Model/Table/StatisticsTableTest.php

| Tickets (_issues_) concernés  | #432 
Migrations!

Kpi global

---

src/Template/Organizations/index.ctp
src/Template/Organizations/submit.ctp
src/Template/Projects/index.ctp
src/Template/Projects/submit.ctp

| Tickets (_issues_) concernés  | #439 
Set helper to understand the notion of organization and projects

add some helper on index and submit page

---

src/Controller/ProjectsController.php
src/Model/Entity/Project.php
src/Template/Users/view.ctp

| Tickets (_issues_) concernés  | #473

Conditioning project

---

statistics.sql

| Tickets (_issues_) concernés  | #507

Populate db for statistics

---

config/routes.php

| Tickets (_issues_) concernés  | #505

fix route to homepage

---

src/Controller/OrganizationsController.php
src/Template/Organizations/my_organizations.ctp
tests/TestCase/Controller/OrganizationsControllerTest.php
webroot/js/organizations/myOrganizations.js

| Tickets (_issues_) concernés  | #512

Add owner badge in myOrganizations

---

src/Template/Pages/contact.ctp

| Tickets (_issues_) concernés  | #515

Change phone number

---

src/Template/Pages/home.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #537

Add facil logo

---

src/Controller/UsersController.php
src/Model/Table/UsersTable.php
src/Template/Users/index.ctp
webroot/js/users/index.js

| Tickets (_issues_) concernés  | #527

Add collumn uni, org, and Student

---

src/Controller/PagesController.php
src/Template/Pages/tv2.ctp

| Tickets (_issues_) concernés  | #541

add tv2 to show stats

---

src/Controller/MissionsController.php
src/Template/Missions/edit.ctp

| Tickets (_issues_) concernés  | #454 
Allow to increment internNrb only if application has been accepted

Conditioning edit mission

---

src/Template/Pages/home.ctp
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #549

Reduce size of partners logo on homepage

---

src/Template/Missions/view.ctp
src/Template/Projects/view.ctp

| Tickets (_issues_) concernés  | #461 
Change 10 to 25 on:
- project view
- mission view

set range to 25 on datatable

---

config/Migrations/20151125202107_create_meetup.php
config/Migrations/20151125212144_add_link_to_meetups.php
populate.sql
src/Controller/MeetupsController.php
src/Model/Entity/Meetup.php
src/Model/Table/MeetupsTable.php
src/Template/Cell/Meetups/list_meetups.ctp
src/Template/Cell/Sidebar/meetup_action.ctp
src/Template/Meetups/add.ctp
src/Template/Meetups/edit.ctp
src/Template/Meetups/index.ctp
src/Template/Pages/home.ctp
src/Template/Pages/meetup.ctp
src/View/Cell/MeetupsCell.php
src/View/Cell/SidebarCell.php
tests/Fixture/MeetupsFixture.php
tests/TestCase/Controller/AppControllerTest.php
tests/TestCase/Controller/MeetupsControllerTest.php
tests/TestCase/Model/Table/MeetupsTableTest.php

| Tickets (_issues_) concernés  | #496

Dynamic meetup

---

config/Migrations/20151126141003_create_news.php
config/Migrations/20151126162259_add_link_to_news.php
populate.sql
src/Controller/NewsController.php
src/Model/Entity/News.php
src/Model/Table/NewsTable.php
src/Template/Cell/News/list_news.ctp
src/Template/Cell/Sidebar/new_action.ctp
src/Template/News/add.ctp
src/Template/News/edit.ctp
src/Template/News/index.ctp
src/Template/Pages/home.ctp
src/View/Cell/NewsCell.php
src/View/Cell/SidebarCell.php
tests/Fixture/NewsFixture.php
tests/TestCase/Controller/AppControllerTest.php
tests/TestCase/Controller/NewsControllerTest.php
tests/TestCase/Model/Table/NewsTableTest.php

| Tickets (_issues_) concernés  | #497

Dynamic news

---

src/Controller/OrganizationsController.php
src/Model/Entity/User.php
src/Template/Organizations/add_member.ctp
src/Template/Organizations/add_owner.ctp

| Tickets (_issues_) concernés  | #488 ; #530

Stop adding yourself admin

---

src/Template/Cell/News/list_news.ctp
src/Template/Pages/news.ctp

| Tickets (_issues_) concernés  | #562

Add news page

---

config/Migrations/20151126225629_create_notifications.php
config/Migrations/20151126230557_add_user_to_notifications.php
src/Controller/AppController.php
src/Controller/NotificationsController.php
src/Model/Entity/Notification.php
src/Model/Table/NotificationsTable.php
src/Template/Notifications/index.ctp
tests/Fixture/NotificationsFixture.php
tests/TestCase/Controller/AppControllerTest.php
tests/TestCase/Controller/NotificationsControllerTest.php
tests/TestCase/Model/Table/NotificationsTableTest.php
webroot/css/ML2-styles.css

| Tickets (_issues_) concernés  | #494

Add notifications

---

src/Controller/OrganizationsController.php
tests/Fixture/OrganizationsMembersFixture.php
tests/Fixture/OrganizationsOwnersFixture.php
tests/Fixture/ProjectsMentorsFixture.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Controller/OrganizationsControllerTest.php

| Tickets (_issues_) concernés  | #526

Unable to quit if mentor of project

---

src/Template/Pages/mission.ctp

Remake mission page

---

src/Template/Pages/survey.ctp

Remake survey page

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #579

add flash render on layout

---

src/Template/Cell/Sidebar/all.ctp
src/View/Cell/SidebarCell.php
webroot/js/main.js

| Tickets (_issues_) concernés  | #576

Set menu dynamic

---

src/Template/Pages/academic.ctp

ETS founding partner

---

src/Controller/AppController.php
src/Controller/NotificationsController.php
src/Template/Layout/default.ctp
src/Template/Notifications/index.ctp

| Tickets (_issues_) concernés  | #574

Implement notification in main bar

---

src/Controller/MissionsController.php

| Tickets (_issues_) concernés  | #529

add verification on user before accept application

---

webroot/less/styles.less

Fix for home for mobile

---

src/Template/Pages/home.ctp

Remove notification from home

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #600

Fix 404 projects when not having org

---

src/Controller/ProjectsController.php
webroot/less/styles.less

| Tickets (_issues_) concernés  | #567

Admin access

---

populate.sql
src/Controller/UsersController.php
tests/TestCase/Controller/UsersControllerTest.php

| Tickets (_issues_) concernés  | #609

[Hotfix] Admin and executive only users/index

---

src/Controller/MissionsController.php

| Tickets (_issues_) concernés  | #544

[Hotfix] Edit mission - reject applications

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #606

[Hotfix] Add all organization in edit project for admin

---

src/Controller/OrganizationsController.php
src/Model/Entity/Organization.php

| Tickets (_issues_) concernés  | #561

[Hotfix] Synch member owner

---

src/Template/Layout/default.ctp
src/Template/Pages/home.ctp

| Tickets (_issues_) concernés  | #613

Remove country flag

---

src/Template/Cell/Sidebar/all.ctp
webroot/less/styles.less

| Tickets (_issues_) concernés  | #570

Change label to arrow in menu and sticky footer

---

src/Template/Pages/contact.ctp
webroot/less/styles.less

| Tickets (_issues_) concernés  | #622
Keys in file are a random application
CHANGE ON PRODUCTION

[Hotfix] Update map for mobile

---

src/Template/Cell/Sidebar/all.ctp
src/Template/Pages/contact.ctp
webroot/less/styles.less

Hotfix to master

---

src/Template/Cell/Sidebar/all.ctp
src/Template/Pages/contact.ctp
webroot/less/styles.less

[Merge] Hotfix to develop

---

src/Template/Cell/Sidebar/new_action.ctp
src/Template/News/add.ctp
src/Template/News/edit.ctp
src/Template/News/index.ctp

| Tickets (_issues_) concernés  | #623

Remake news admin page

---

src/Controller/MissionsController.php
src/Template/Cell/Sidebar/all.ctp
src/Template/Missions/index.ctp
webroot/js/missions/index.js

| Tickets (_issues_) concernés  | #634

Mission index

---

config/Migrations/20151204143331_add_social_network_to_users.php
config/Migrations/20151204143435_add_public_email_to_users.php
config/Migrations/20151204143507_add_interest_to_users.php
src/Model/Entity/User.php
src/Model/Table/UsersTable.php
src/Template/Cell/Sidebar/user.ctp
src/Template/Users/edit.ctp
src/Template/Users/view.ctp
tests/Fixture/UsersFixture.php
tests/TestCase/Model/Table/UsersTableTest.php
webroot/less/styles.less

| Tickets (_issues_) concernés  | #624

Upgrade profile information

---

src/Template/Cell/Sidebar/meetup_action.ctp
src/Template/Meetups/add.ctp
src/Template/Meetups/edit.ctp
src/Template/Meetups/index.ctp
src/Template/News/add.ctp
src/Template/News/edit.ctp
src/Template/News/index.ctp

| Tickets (_issues_) concernés  | #639

Remake meetups admin page

---

src/Template/Cell/Sidebar/organization.ctp

| Tickets (_issues_) concernés  | #645

debug icon of approve organization in sidebar

---

composer.json
src/Template/Meetups/add.ctp
src/Template/Meetups/edit.ctp
src/Template/Meetups/index.ctp
src/Template/Missions/view.ctp
src/Template/News/add.ctp
src/Template/News/edit.ctp
src/Template/Organizations/view.ctp
src/Template/Projects/view.ctp
src/Template/Users/view.ctp

| Tickets (_issues_) concernés  | #643

Transform markdown images into links

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | #641

add where clause on organization filter in project index

---

src/Controller/ProjectsController.php
src/Template/Projects/index.ctp

| Tickets (_issues_) concernés  | #644

Change filter from select to text for org

---

config/Migrations/20151208181251_add_is_professor_to_users.php
src/Model/Entity/User.php
src/Template/Cell/Sidebar/user.ctp
src/Template/Users/edit.ctp
tests/Fixture/UsersFixture.php
tests/TestCase/Model/Table/UsersTableTest.php
webroot/js/users/edit.js
webroot/less/styles.less

| Tickets (_issues_) concernés  | #656

Add is professor

---

src/Controller/UsersController.php

| Tickets (_issues_) concernés  | #650

add public email when register

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #649

Close <a> tag in language selector

---

src/Template/Applications/accepted.ctp

| Tickets (_issues_) concernés  | #671

[HOTFIX] add begin form on accept application

---

src/Template/Pages/statistics.ctp

| Tickets (_issues_) concernés  | #661

add translation text in statistics

---

src/Controller/OrganizationsController.php
src/Controller/UsersController.php
src/Template/Users/view.ctp
tests/TestCase/Controller/OrganizationsControllerTest.php
update.md
webroot/less/styles.less

| Tickets (_issues_) concernés  | #472

Conditioning organizations

---

src/Template/Cell/Sidebar/user.ctp

| Tickets (_issues_) concernés  | #679

Span close tag

---

config/routes.php
src/Controller/PagesController.php
src/Template/Cell/Sidebar/all.ctp
src/Template/Meetups/add.ctp
src/Template/Meetups/edit.ctp
src/Template/Meetups/index.ctp
src/Template/News/add.ctp
src/Template/News/edit.ctp
src/Template/News/index.ctp
src/Template/Pages/administration.ctp

| Tickets (_issues_) concernés  | #660

Add panel administration

---

src/Model/Table/UsersTable.php

| Tickets (_issues_) concernés  | #678

Put skills field to not required

---

config/Migrations/20151208210056_add_more_infos_to_applications.php
src/Controller/ApplicationsController.php
src/Controller/MissionsController.php
src/Model/Entity/Application.php
src/Model/Table/ApplicationsTable.php
src/Model/Table/TypeMissionsTable.php
src/Template/Applications/view.ctp
src/Template/Missions/apply.ctp
src/Template/Missions/view.ctp
src/Template/Users/edit.ctp
tests/Fixture/ApplicationsFixture.php
tests/TestCase/Controller/ApplicationsControllerTest.php
tests/TestCase/Model/Table/ApplicationsTableTest.php
webroot/js/missions/apply.js
webroot/js/missions/viewMentor.js
webroot/less/styles.less

| Tickets (_issues_) concernés  | #653

Detail application

---

src/Template/Pages/home.ctp
src/Template/Users/recover_password.ctp
webroot/less/styles.less

| Tickets (_issues_) concernés  | #680 #683

Mobile fix

---

src/Controller/ApplicationsController.php
src/Controller/OrganizationsController.php
src/Controller/ProjectsController.php
src/Model/Entity/Notification.php
tests/Fixture/NotificationsFixture.php
tests/TestCase/Model/Table/NotificationsTableTest.php

| Tickets (_issues_) concernés  | #647

Add notifications in controller

---

config/Migrations/20151209154349_add_professor_to_missions.php
populate.sql
src/Controller/MissionsController.php
src/Model/Entity/Mission.php
src/Model/Entity/TypeMission.php
src/Model/Table/MissionsTable.php
src/Template/Cell/Sidebar/mission.ctp
src/Template/Missions/edit_mentor.ctp
src/Template/Missions/edit_professor.ctp
src/Template/Missions/index.ctp
src/Template/Missions/view.ctp
src/Template/Projects/view.ctp
tests/Fixture/MissionsFixture.php
tests/Fixture/TypeMissionsFixture.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Model/Table/MissionsTableTest.php
tests/TestCase/Model/Table/TypeMissionsTableTest.php

| Tickets (_issues_) concernés  | #664

System professor on mission

---

src/Controller/MissionsController.php
src/Template/Missions/view.ctp
tests/Fixture/UsersFixture.php
tests/TestCase/Controller/MissionsControllerTest.php

| Tickets (_issues_) concernés  | #688

forbid mentor to apply on his mission

---

src/Controller/MissionsController.php

| Tickets (_issues_) concernés  | #693

Fix application so everyone but mentor can apply

---

src/Template/Users/edit.ctp

| Tickets (_issues_) concernés  | #703

delete field email in user edit

---

src/Template/Pages/industry.ctp

| Tickets (_issues_) concernés  | #709

change typo of SFL in partners page

---

src/Template/Organizations/view.ctp

| Tickets (_issues_) concernés  | #711

Remove link when no access to archived project

---

src/Template/Users/register.ctp

| Tickets (_issues_) concernés  | #716

Remove TOS checkbox

---

src/Template/Organizations/view.ctp

| Tickets (_issues_) concernés  | #711

Add on non-archived project

---

src/Template/Organizations/view.ctp
src/Template/Users/register.ctp

[Merge] Hotfix -> master

---

src/Template/Users/view.ctp

| Tickets (_issues_) concernés  | #713

change conditionning of link project to project

---

src/Template/Users/view.ctp

| Tickets (_issues_) concernés  | #727

update badge on user view projetc/organization

---

src/Controller/PagesController.php

| Tickets (_issues_) concernés  | #730

Apply condition for the projects count

---

src/Controller/PagesController.php

| Tickets (_issues_) concernés  | #733

Fix projects and missions number for stats + tv page

---

populate.sql

| Bug fix ?                     | no
| New functionnality ?          | no
| Tickets (_issues_) reference  | #738

INSERT INTO -> REPLACE

---

config/Migrations/20151215212933_add_datetime_to_projects.php
config/Migrations/20151215212949_add_datetime_to_organizations.php
update.md

| Bug fix ?                     | No
| New functionnality ?          | No
| Tickets (_issues_) reference  | #662

Add field datetime

---

src/Template/Missions/add.ctp
src/Template/Missions/edit.ctp
src/Template/Projects/submit.ctp
webroot/js/missions/add.js
webroot/js/missions/edit.js
webroot/js/projects/submit.js

| Bug fix ?                     | Non
| New functionnality ?          | Oui
| Tickets (_issues_) reference  | #531 ;

More info missions

---

tests/Fixture/PermissionsFixture.php
tests/Fixture/PermissionsTypeUsersFixture.php
tests/TestCase/Controller/MeetupsControllerTest.php

| Bug fix ?                     | Non
| New functionnality ?          | Non
| Tickets (_issues_) reference  | #220

Meetups controller test

---

src/Template/Cell/News/list_news.ctp
src/Template/News/add.ctp
src/Template/News/edit.ctp

Markdown editor plugin in add.ctp and edit.ctp
Parsedown in list_news.ctp
fix 772

feat(front): Use markdown for news description

---

.gitignore
doc/IPE-relationship-activity.uml
doc/IPE-table-changes.uml

| Nouvelle Fonctionnalité ?     | oui
| Tickets (_issues_) concernés  | 791

doc(uml): IPE solution to 791

---

src/Template/Layout/default.ctp

| Tickets (_issues_) concernés  | #682
1) open chrome developer
2) select a mobile screen size
3) go to project list 
4) scroll down
5) push menu button in top right
should scroll to the top.

scroll up fix for github issue #682

---

src/Model/Table/ApplicationsTable.php

| Tickets (_issues_) concernés  | #823

fix(model): Email not unique

---

config/Migrations/20160127163040_create_users_type_missions.php
config/app.php
src/Controller/UsersController.php
src/Model/Entity/UsersTypeMission.php
src/Model/Table/UsersTable.php
src/Model/Table/UsersTypeMissionsTable.php
src/Shell/SendMailShell.php
src/Template/Email/html/new_missions.ctp
src/Template/Email/text/new_missions.ctp
src/Template/Users/edit.ctp
src/Template/Users/view.ctp
tests/Fixture/UsersTypeMissionsFixture.php
tests/TestCase/Controller/UsersControllerTest.php
tests/TestCase/Model/Table/UsersTypeMissionsTableTest.php

729 mission seeked

---

src/Template/Applications/view.ctp

fix(applications): Remove type_mission from view

---

tests/Fixture/NotificationsFixture.php
tests/TestCase/Controller/NotificationsControllerTest.php

test(notifications): markAsRead

---

tests/TestCase/Controller/ApplicationsControllerTest.php
tests/TestCase/Controller/MissionsControllerTest.php
tests/TestCase/Controller/NotificationsControllerTest.php
tests/TestCase/Controller/OrganizationsControllerTest.php
tests/TestCase/Controller/PagesControllerTest.php
tests/TestCase/Controller/ProjectsControllerTest.php
tests/TestCase/Controller/SvnsControllerTest.php
tests/TestCase/Controller/TypeUsersControllerTest.php
tests/TestCase/Controller/UniversitiesControllerTest.php
tests/TestCase/Controller/UsersControllerTest.php

fix(tests): News fixtures in controllers tests

---

src/Template/Layout/default.ctp

fix(frontend): Set title for all pages

---

src/Model/Entity/User.php
src/Template/Missions/view.ctp
tests/Fixture/ApplicationsFixture.php
tests/Fixture/MissionsFixture.php
tests/Fixture/UsersFixture.php
tests/TestCase/Model/Table/UsersTableTest.php

902 unaccept

---

.gitignore

fix(gitignore): Ignore phpunit.xml

---

webroot/less/styles.less

fix(frontend): make sections breathe with padding

---

src/Template/Missions/index.ctp

fix(frontend): Remove sorting for organizations

---

src/Controller/MissionsController.php

codestyle(missions): Fix indentation

---

src/Controller/UsersController.php

refactor(users): _sendResetPasswordEmail method

---

webroot/less/styles.less

fix(carousel): Only show one type of carousel

---

src/Template/Cell/Sidebar/all.ctp

feat(sidebar): wiki link

---

src/Template/Pages/home.ctp

fix(carousel): event as first element in carousel

---

webroot/less/styles.less

fix(home): default value for position

---

src/Controller/UsersController.php
src/Template/Users/edit.ctp
src/Template/Users/register.ctp
src/Template/Users/register_industry.ctp
src/Template/Users/register_professor.ctp
src/Template/Users/register_student.ctp
src/Template/Users/register_student_optional.ctp
tests/TestCase/Controller/UsersControllerTest.php
webroot/js/users/registerStudentOptional.js
webroot/less/carousel.less
webroot/less/colors.less
webroot/less/register-button.less
webroot/less/styles.less

994 register

---

src/Template/Missions/index.ctp
webroot/less/filter-box.less
webroot/less/styles.less

feat(missions): padding right filter box

---

src/Template/Cell/Sidebar/all.ctp
webroot/less/first-news.less
webroot/less/styles.less

fix(first-news): first-news mobile

---

src/Template/Users/register.ctp

fix(register): Smaller heading element

---

src/Template/Missions/index.ctp
webroot/less/filter-box.less

feat(missions): top margin professor box

---

src/Template/Missions/index.ctp
webroot/less/paginator.less

feat(mobile): Show only one column in mobile

---

src/Template/Pages/association.ctp
src/Template/Pages/home.ctp
webroot/less/home.less

fix(sponsor): FACIL is not a sponsor

---

src/Template/Layout/default.ctp

fix(top-navbar): Link to github.io

---

src/Template/Pages/home.ctp

fix(carousel): Remove luc workshop

---

src/Template/Pages/home.ctp

fix(carousel): Remove mcgamejam

---

src/Controller/OrganizationsController.php

fix(organizations): redirect to projects submit

---

src/Controller/ProjectsController.php
tests/TestCase/Controller/ProjectsControllerTest.php

fix(projects): Change to type_mission

---

src/Template/Users/register_student.ctp

translation(users): Not specified

---

config/Migrations/20160510151928_modify_users_to_integer.php
src/Controller/UsersController.php
src/Template/Users/edit.ctp

| Tickets (_issues_) concernés  | [1107]

modification de la table user

---

src/Controller/PagesController.php

refactorisation du code pour l'upload

---

src/Controller/PagesController.php

amelioration du message d'erreur pour le systeme d'upload

---

src/Controller/PagesController.php

test module upload

---

src/Controller/PagesController.php

Willkoua test module upload

---

src/Controller/PagesController.php
src/Template/Pages/administration.ctp

correction des vues et du controller pour la page d'administration

---

src/Controller/PagesController.php
src/Template/Pages/home.ctp

Add img home

---

config/app.php
src/Template/Users/edit.ctp

| Tickets (_issues_) concernés  | [1090]

Modification du champs competence

---

config/app.php
src/Template/Users/edit.ctp

1090 user competence

---

src/Controller/PagesController.php

| Tickets (_issues_) concernés  | [1176]

modification du mode des dossiers contenants les images

---

src/Controller/PagesController.php
src/Template/Pages/administration.ctp

| Nouvelle Fonctionnalité ?     | [oui]
| Tickets (_issues_) concernés  | [1180]

1180 update home admin

---

config/Migrations/20160602174229_update_projetc_fileds.php
src/Model/Entity/Project.php
src/Model/Table/ProjectsTable.php

| Tickets (_issues_) concernés  | [1196]

resolution du bug de l'issue 1196

---

config/Migrations/20160603154418_update_user_isprofessor.php
config/Migrations/20160607132004_update_user_isprofessor.php

| Tickets (_issues_) concernés  | [954]

954 update usrs fields

---

src/Template/Pages/home.ctp

| Correction de bugs ?          | [non]

ajout d'un bouton vers la page de creation de projet

---

src/Template/Missions/view.ctp
webroot/js/missions/viewMentor.js

| Correction de bugs ?          | [non]
| Nouvelle Fonctionnalité ?     | [oui]
| Tickets (_issues_) concernés  | [1213]

ajout dun popup avant la validation dun cadidat sur une mission

---

src/Controller/ProjectsController.php
src/Template/Missions/view.ctp

| Tickets (_issues_) concernés  | [1212, 1215]

supression des listes des utilisateurs les missions archivees

---

src/Controller/ProjectsController.php

| Tickets (_issues_) concernés  | [1203]

resolution du bug de la requete de recherche de projet

---

config/bootstrap.php

| Tickets (_issues_) concernés  | #1224 , #1225

Fixing broken missions under projects and organizations lists

---

src/Template/Layout/default.ctp
src/Template/Pages/contact.ctp

| Correction de bugs ?          | [non]
| Tickets (_issues_) concernés  | [1228]

Add local number
